### ISSUE TITLE
Redesign Wizard and Menu

### ISSUE THREAD

**Issue by Heiss** [Sciebo-RDS/RDS-Web#17]
- [x] Menu is not visible as long as the wizard was not processed
- [x] Menu gets a gear icon in footer, so there can be added settings things
  - [x] set light / dark mode as icons like vuetify documentary
  - [x] account management link to redirect to an iframe, so the user can be informed about the consequences of an account removal
- [x] multiple iframes on website
  - [x] welcome page (before setup / wizard workflow)
  - [x] help page
  - [x] start page (after setup / wizard)
  - [x] account removal page (when the user wants to delete the RDS account)
- [x] "jetzt starten" on welcome page redirects to oauth2 owncloud page
  - [x] after successful activation, the user will see the services view without any menu (with the v-card on top for informations)

**Comment by juriroemer** [comment]
- [ ] expension panels have a description of the services, which will be set through the port in backend
