### ISSUE TITLE
replace add service functionality in settings page with dedicated "services" page

### ISSUE THREAD

**Issue by juriroemer** [Sciebo-RDS/RDS-Web#19]
- [x] service page is like projects page but for services
- [x] services have labels "activated" oder "not activated"
- [x] expansion panels contain description of the services (served through the ports object by the backend)
- [x] expansion panels contain buttons do activate/deactivate the service
- [x] services page will have "activate at least one service to use RDS" note, if no services are activated

**Comment by Heiss** [comment]
done
